# Generated by Django 3.2.8 on 2021-10-07 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("teams", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(verbose_name="Время проведения"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Название турнира"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=1000,
                        null=True,
                        verbose_name="Описание турнира",
                    ),
                ),
                (
                    "number_teams_match",
                    models.IntegerField(
                        default=2,
                        verbose_name="Количество команд в каждом матче на этом турнире",
                    ),
                ),
                (
                    "educational_location_limit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.location",
                        verbose_name="Ограничение по географическому расположению",
                    ),
                ),
                (
                    "educational_type_limit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.educationaltype",
                        verbose_name="Ограничение по типу учебного заведения",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_tournament",
                        to="games.game",
                        verbose_name="Игра турнира",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentEventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        verbose_name="Название типа события на турнире",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="Время события")),
                (
                    "tournament",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_event",
                        to="tournaments.tournament",
                        verbose_name="Турнир",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_event_type",
                        to="tournaments.tournamenteventtype",
                        verbose_name="Тип события",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(verbose_name="Номер раунда в матче"),
                ),
                (
                    "date_created",
                    models.DateTimeField(verbose_name="Время проведения"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds_match",
                        to="tournaments.match",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        related_name="rounds",
                        to="teams.Team",
                        verbose_name="Команды матча",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournaments.tournament",
                verbose_name="Турнир",
            ),
        ),
    ]
