# Generated by Django 3.2.8 on 2021-10-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_quantity_players"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="confirmed_teams",
            field=models.ManyToManyField(
                related_name="confirmed_teams",
                to="teams.Team",
                verbose_name="Команды подтвердившие участие",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="registered_teams",
            field=models.ManyToManyField(
                related_name="registered_teams",
                to="teams.Team",
                verbose_name="Зарегистрированные команды",
            ),
        ),
    ]
