# Generated by Django 3.2.8 on 2021-10-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_auto_20211020_1651"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="allowed_quantity_players_in_team",
            field=models.IntegerField(
                default=5,
                verbose_name="Допустимое количество игроков в команде",
            ),
        ),
    ]
