# Generated by Django 3.2.8 on 2021-10-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_quantity_players"),
        ("tournaments", "0003_tournament_allowed_quantity_players_in_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="confirmed_teams",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="confirmed_teams",
                to="teams.Team",
                verbose_name="Команды подтвердившие участие",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="registered_teams",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="registered_teams",
                to="teams.Team",
                verbose_name="Зарегистрированные команды",
            ),
        ),
    ]
