# Generated by Django 3.2.8 on 2021-10-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_quantity_players"),
        ("tournaments", "0004_auto_20211020_1711"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="number",
            field=models.IntegerField(
                default=0, verbose_name="Номер матча в турнирной сетке"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="quantity_wins",
            field=models.IntegerField(
                default=1, verbose_name="Количество побед в раундах"
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds_winner",
                to="teams.team",
                verbose_name="Победитель",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="confirmed_teams",
            field=models.ManyToManyField(
                blank=True,
                related_name="confirmed_teams",
                to="teams.Team",
                verbose_name="Команды подтвердившие участие",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="registered_teams",
            field=models.ManyToManyField(
                blank=True,
                related_name="registered_teams",
                to="teams.Team",
                verbose_name="Зарегистрированные команды",
            ),
        ),
    ]
