# Generated by Django 3.2.8 on 2021-10-29 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0005_auto_20211028_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="next_match",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previous_match",
                to="tournaments.match",
                verbose_name="Следующий матч",
            ),
        ),
    ]
