# Generated by Django 3.2.8 on 2021-10-31 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_quantity_players"),
        ("tournaments", "0006_match_next_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_winner",
                to="teams.team",
                verbose_name="Победитель",
            ),
        ),
    ]
