# Generated by Django 3.2.8 on 2021-12-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0008_auto_20211209_0703"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="description",
            field=models.TextField(
                max_length=1500, null=True, verbose_name="Описание турнира"
            ),
        ),
    ]
