# Generated by Django 3.2.8 on 2021-12-17 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("tournaments", "0009_alter_tournament_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="referee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_referee",
                to="users.user",
                verbose_name="Судья туринира",
            ),
        ),
    ]
