# Generated by Django 3.2.8 on 2022-01-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0010_tournament_referee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("happening", "Начало турнира"),
                    ("confirmation", "Подтверждения"),
                    ("registration", "Регистрации"),
                ],
                default="happening",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="TournamentEventType",
        ),
    ]
