# Generated by Django 3.2.8 on 2022-01-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0011_auto_20220104_1122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentevent",
            name="type",
            field=models.IntegerField(
                choices=[
                    (3, "Начало турнира"),
                    (2, "Подтверждения"),
                    (1, "Регистрации"),
                ],
                default=1,
            ),
        ),
    ]
