# Generated by Django 3.2.8 on 2022-05-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220518_2227'),
        ('tournaments', '0013_alter_match_next_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='educational_location_limit',
        ),
        migrations.AddField(
            model_name='tournament',
            name='federal_districts_limit',
            field=models.ManyToManyField(blank=True, null=True, to='users.FederalDistricts', verbose_name='Ограничение по географическому расположению'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='location_limit',
            field=models.ManyToManyField(blank=True, null=True, to='users.Location', verbose_name='Ограничение по географическому расположению'),
        ),
    ]
