# Generated by Django 3.2.8 on 2022-05-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220518_2227'),
        ('tournaments', '0014_auto_20220518_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='federal_districts_limit',
            field=models.ManyToManyField(to='users.FederalDistricts', verbose_name='Ограничение по географическому расположению'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location_limit',
            field=models.ManyToManyField(to='users.Location', verbose_name='Ограничение по географическому расположению'),
        ),
    ]
