# Generated by Django 3.2.8 on 2022-05-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_location_federal_districts'),
        ('tournaments', '0015_auto_20220518_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='federal_districts_limit',
            field=models.ManyToManyField(blank=True, to='users.FederalDistricts', verbose_name='Ограничение по географическому расположению (федиральный округ)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location_limit',
            field=models.ManyToManyField(blank=True, to='users.Location', verbose_name='Ограничение по географическому расположению'),
        ),
    ]
