# Generated by Django 3.2.8 on 2022-06-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_location_federal_districts'),
        ('tournaments', '0017_auto_20220604_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_referee', to='users.user', verbose_name='Судья матча'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='referee',
            field=models.ManyToManyField(blank=True, related_name='tournament_referee', to='users.User', verbose_name='Судьи туринира'),
        ),
    ]
