# Generated by Django 3.2.8 on 2022-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_auto_20220604_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='count_wins_in_match',
            field=models.IntegerField(default=2, verbose_name='Необходимое количество побед в раундах, для победы в матче'),
        ),
    ]
