# Generated by Django 3.2.8 on 2022-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_tournament_count_wins_in_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentevent',
            name='send_notification',
            field=models.BooleanField(default=True, verbose_name='Не рассылать уведомления пользователям'),
        ),
    ]
