# Generated by Django 3.2.8 on 2022-06-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_tournamentevent_send_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='study_team',
            field=models.BooleanField(default=False, verbose_name='Участвовать могут только сборные учебных заведений'),
        ),
    ]
