# Generated by Django 3.2.8 on 2022-07-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220701_1637'),
        ('tournaments', '0021_tournament_study_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='referee',
            field=models.ManyToManyField(related_name='tournament_referee', to='users.User', verbose_name='Судьи туринира'),
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='type',
            field=models.IntegerField(choices=[(3, 'Начало турнира'), (2, 'Подтверждения'), (1, 'Регистрации')], default=1, verbose_name='тип'),
        ),
    ]
