# Generated by Django 3.2.8 on 2022-07-01 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_auto_20220701_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_status', models.IntegerField(choices=[(1, 'Зарегестрированным'), (2, 'Играющим'), (3, 'Не рассылать')], default=3)),
                ('text', models.CharField(max_length=5000, verbose_name='Текст уведомления')),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Дата создания уведомления')),
                ('send', models.BooleanField(default=False, verbose_name='Разослать')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_notification', to='tournaments.tournament', verbose_name='Турнир')),
            ],
        ),
    ]
