# Generated by Django 3.2.8 on 2022-07-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_tournamentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=1000, verbose_name='Максимальное количество участвноков'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_teams',
            field=models.IntegerField(default=2, verbose_name='Минимальное количество участников'),
        ),
    ]
