# Generated by Django 3.2.8 on 2022-07-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_auto_20220701_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивирована'),
        ),
    ]
