# Generated by Django 3.2.8 on 2022-07-03 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_auto_20220702_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='number_teams_match',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(200)], verbose_name='Количество команд в каждом матче на этом турнире'),
        ),
    ]
