# Generated by Django 3.2.8 on 2022-07-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0027_alter_tournament_number_teams_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Этап'),
        ),
    ]
