# Generated by Django 3.2.8 on 2022-07-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0028_alter_match_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
    ]
