# Generated by Django 3.2.8 on 2022-07-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0029_match_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='next_match',
            new_name='next_match_for_winner',
        ),
    ]
