# Generated by Django 3.2.8 on 2022-07-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0030_rename_next_match_match_next_match_for_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='grid',
            field=models.IntegerField(choices=[(1, 'single elimination'), (2, 'double elimination')], default=1, verbose_name='Сетка'),
        ),
    ]
