# Generated by Django 3.2.8 on 2022-07-09 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0031_tournament_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='next_match_for_loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_loser_match', to='tournaments.match', verbose_name='Следующий матч для проигравшего'),
        ),
        migrations.AlterField(
            model_name='match',
            name='next_match_for_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_winner_match', to='tournaments.match', verbose_name='Следующий матч для победителя'),
        ),
    ]
