# Generated by Django 3.2.8 on 2022-12-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0033_match_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsgoRound',
            fields=[
                ('round_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tournaments.round')),
                ('round_map', models.IntegerField(choices=[(1, 'Anubis'), (2, 'Inferno'), (3, 'Overpass'), (4, 'Mirage'), (5, 'Ancient'), (6, 'Nuke'), (7, 'Vertigo')], verbose_name='карта раунда')),
            ],
            bases=('tournaments.round',),
        ),
    ]
