# Generated by Django 3.2.8 on 2022-12-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0034_csgoround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csgoround',
            name='round_map',
            field=models.IntegerField(blank=True, choices=[(1, 'Anubis'), (2, 'Inferno'), (3, 'Overpass'), (4, 'Mirage'), (5, 'Ancient'), (6, 'Nuke'), (7, 'Vertigo')], null=True, verbose_name='карта раунда'),
        ),
    ]
