# Generated by Django 3.2.8 on 2022-12-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_teaminvites_type'),
        ('tournaments', '0039_csgopeakstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='csgopeakstage',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='команда'),
        ),
    ]
