# Generated by Django 3.2.8 on 2021-12-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=512, verbose_name="Вложение"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Код кнопки"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Текст кнопки"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        null=True, verbose_name="полезная нагрузка"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("mailing", "mailing"), ("personal", "personal")],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="delivered",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("sending", "sending"),
                    ("done", "done"),
                ],
                default="new",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="NotificationStatus",
        ),
        migrations.DeleteModel(
            name="NotificationType",
        ),
        migrations.AddField(
            model_name="notification",
            name="attachment",
            field=models.ManyToManyField(
                blank=True, to="users.Attachment", verbose_name="Вложение"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="endpoint",
            field=models.ManyToManyField(
                blank=True,
                to="users.Endpoint",
                verbose_name="Кнопки в уведомлении",
            ),
        ),
    ]
