# Generated by Django 3.2.8 on 2021-12-15 11:21

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20211215_1121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="delivery_date",
            field=models.DateTimeField(
                default=datetime.datetime.utcnow,
                verbose_name="Время доставки уведомления",
            ),
        ),
    ]
