# Generated by Django 3.2.8 on 2021-12-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20211216_1550"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernotification",
            name="delivered",
        ),
        migrations.AddField(
            model_name="usernotification",
            name="status",
            field=models.IntegerField(
                choices=[(1, "new"), (2, "sending"), (3, "fail"), (4, "done")],
                default=1,
            ),
        ),
    ]
