# Generated by Django 3.2.8 on 2022-04-27 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_next_verification',
            field=models.DateField(default=datetime.datetime.utcnow, verbose_name='дата следующей верификации'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'mailing'), (2, 'personal')], default=2),
        ),
    ]
