# Generated by Django 3.2.8 on 2022-05-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220518_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='federal_districts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federation_subjects', to='users.federaldistricts', verbose_name='Федеральный округ'),
        ),
    ]
