# Generated by Django 3.2.8 on 2022-06-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_location_federal_districts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationalInstitution',
            new_name='UserEducation',
        ),
    ]
