# Generated by Django 3.2.8 on 2022-06-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_educationalinstitution_usereducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название учебного заведения')),
            ],
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to='users.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to='users.educationaltype', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_education', to='users.institute', verbose_name='Учебное заведение'),
        ),
    ]
