# Generated by Django 3.2.8 on 2022-06-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220613_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send',
            field=models.BooleanField(default=False, verbose_name='Разослать'),
        ),
    ]
