# Generated by Django 3.2.8 on 2022-06-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20220531_0004'),
        ('users', '0016_notification_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_subscription',
            field=models.ManyToManyField(blank=True, related_name='users', to='games.Game', verbose_name='Игры по который пользователь будет получать уведомления'),
        ),
    ]
