# Generated by Django 3.2.8 on 2022-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_game_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_sate',
            field=models.IntegerField(choices=[(1, 'Настройка уведомлений'), (2, 'Привязка игровый аккаунтов'), (3, 'Привязка учебного заведения'), (3, 'Главное меню')], default=1),
        ),
    ]
