# Generated by Django 3.2.8 on 2022-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20220531_0004'),
        ('users', '0021_auto_20220701_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='games_limit',
            field=models.ManyToManyField(blank=True, to='games.Game', verbose_name='Рассылка по играм'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='confirmed_users',
            field=models.BooleanField(default=False, verbose_name='Расзослвать только подтвержденным учетным записям'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='educational_type_limit',
            field=models.ManyToManyField(blank=True, to='users.EducationalType', verbose_name='Рассылка по типу учебного заведения'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='federal_districts_limit',
            field=models.ManyToManyField(blank=True, to='users.FederalDistricts', verbose_name='Рассылка по географическому расположению (федиральный округ)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='location_limit',
            field=models.ManyToManyField(blank=True, to='users.Location', verbose_name='Рассылка по географическому расположению'),
        ),
    ]
