# Generated by Django 3.2.8 on 2022-07-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220701_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='changeable',
            field=models.BooleanField(default=True, verbose_name='Разрешено редактирование?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='confirmed_users',
            field=models.BooleanField(default=False, verbose_name='Только для подтвержденных пользователей'),
        ),
    ]
