# Generated by Django 3.2.8 on 2022-07-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_usernotification_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('text', 'type', 'endpoints', 'system')},
        ),
    ]
