# Generated by Django 3.2.8 on 2022-07-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_notification_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.CharField(max_length=240, null=True, verbose_name='вк id'),
        ),
    ]
