# Generated by Django 3.2.8 on 2022-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_vk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='platform_token',
            field=models.CharField(default='', max_length=500, verbose_name='ID или токен пользователя'),
        ),
        migrations.AlterUniqueTogether(
            name='gameaccount',
            unique_together={('user', 'platform')},
        ),
    ]
