# Generated by Django 3.2.8 on 2022-07-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20220709_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vk_id',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='вк id'),
        ),
    ]
