# Generated by Django 3.2.8 on 2022-07-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_user_vk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccount',
            name='nick_name',
            field=models.CharField(blank=True, default='Ник', max_length=500, null=True, verbose_name='Ник пользователя на платформе'),
        ),
    ]
