# Generated by Django 3.2.8 on 2021-10-07 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=500, verbose_name="Название команды"
                    ),
                ),
                (
                    "captain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_captaining",
                        to="users.user",
                        verbose_name="Капитан команды",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="games.game",
                        verbose_name="Игра команды",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teams",
                        to="users.User",
                        verbose_name="Члены команды",
                    ),
                ),
            ],
        ),
    ]
