# Generated by Django 3.2.8 on 2021-10-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="quantity_players",
            field=models.IntegerField(
                default=5, verbose_name="Количество игроков в команде"
            ),
        ),
    ]
