# Generated by Django 3.2.8 on 2021-11-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_team_quantity_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="archived",
            field=models.BooleanField(
                default=False, verbose_name="Архивирована"
            ),
        ),
    ]
