# Generated by Django 3.2.8 on 2021-12-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_team_archived"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="quantity_players",
            new_name="players_count",
        ),
    ]
