# Generated by Django 3.2.8 on 2022-06-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_rename_quantity_players_team_players_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Название команды'),
        ),
    ]
