# Generated by Django 3.2.8 on 2022-06-13 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_notification_send'),
        ('teams', '0005_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Дата приглашения')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Игрок')),
            ],
        ),
    ]
