# Generated by Django 3.2.8 on 2022-06-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_teaminvites'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvites',
            name='type',
            field=models.IntegerField(choices=[(1, 'новое'), (2, 'отклоненное')], default=1),
        ),
    ]
