# Generated by Django 3.2.8 on 2022-05-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_single'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество игроков')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='single',
        ),
        migrations.AddField(
            model_name='game',
            name='player_count',
            field=models.ManyToManyField(to='games.PlayerCount', verbose_name='количество игроков в команде'),
        ),
    ]
