stages:
  - test
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  CONTAINER_NAME: $CI_PROJECT_PATH_SLUG-$CI_PROJECT_ID


lint:
  image: python:3.9
  stage: test
  services:
    - docker:dind
  script:
    - pip install pylint==2.11.1
    - pylint ./cyberbot/* ./games/* ./teams/* ./tournaments/* ./users/*
  only:
    - merge_requests


publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  only:
    - dev

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - export
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "mkdir -p env/$CI_PROJECT_ID"
    - scp -i $ID_RSA $DEV_ENV $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/env/$CI_PROJECT_ID/.env
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f $CONTAINER_NAME || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run --restart always -v /tmp/cyberbot/core/static/:/app/static/ --env-file=env/$CI_PROJECT_ID/.env -d -p $PORT:5000 --name $CONTAINER_NAME $TAG_COMMIT"
  only:
    - dev


prod_publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  only:
    - master

prod_deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:18.09.7
  tags:
    - bonch-server
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $TAG_COMMIT
    - docker container rm -f $CONTAINER_NAME || true
    - docker run --restart always --env-file=$PROD_ENV -d --network host -p $PROD_PORT:5001 --name $CONTAINER_NAME $TAG_COMMIT
  only:
    - master
